Уплотнить заданную матрицу, удаляя из нее строки и столбцы, заполненные нулями. Найти
номер первой из строк, содержащих хотя бы один положительный элемент.

In [42]:
import numpy as np
m = np.array([[0, 0, 1, 1, 0, 0, 1, 0, 1, 0],
             [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
             [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
             [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
             [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
             [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
             [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
             [0, 0, 1, 0, 1, 0, 1, 0, 1, 0]])
idx = np.all(m==0, axis=0)
a = np.delete(m, np.nonzero(idx), axis=1)
idx = np.all(a==0, axis=1)
a = np.delete(a, np.nonzero(idx), axis=0)
print(a)
b = np.where(m > 0)[0][0]
print("Строка вхождения первого положительного элемента: ", b+1)

[[1 1 0 1 1]
 [1 0 1 1 1]
 [1 0 1 1 1]
 [1 0 1 1 1]
 [1 0 1 1 1]
 [1 0 1 1 1]
 [1 0 0 0 0]
 [1 0 1 1 1]]
Строка вхождения первого положительного элемента:  1
